### ISSUE TITLE
Provision Ansible Automation Platform on Azure

### ISSUE THREAD

**Issue by ivandov** [IBM/zmodstack-deploy#101]
### Description

Create an instance of AAP on Azure

### Possible Options
1. Use the [self-managed AAP install](https://portal.azure.com/#create/redhat.rh-ansible-self-managedrh-aap2)
2. Use the [managed AAP install](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/redhat.rhaapomsa?exp=ubp8&tab=Overview&signInModalType=1&ctaType=1)

### Further considerations
Create an ansible workflow to stop/start an existing Azure zmodstack cluster, using existing automation scripts created by @nikita-hakari

**Comment by midhun6989** [comment]
AAP (managed instance) has been setup successfully in Azure. Able to execute Ansible Playbooks from AAP to OCP Clusters in Azure and AWS.

**Comment by midhun6989** [comment]
@Nikita Hakari I had gone through your `cluster-restart.sh` script. Considering the Red Hat [documentation](https://docs.openshift.com/container-platform/4.14/backup_and_restore/graceful-cluster-shutdown.html) for Cluster Shutdown as a benchmark, It has the required steps like cordon nodes, drain nodes etc. I reckon, steps to be modified to shutdown the cluster rather than its reboot. 
As per the Red Hat [documentation](https://docs.openshift.com/container-platform/4.14/backup_and_restore/graceful-cluster-restart.html) for Cluster Restart, we might have to use our cloud provider’s web console. 
Post which uncordon nodes has to be done to bring back the cluster to its original state.
So the sequence of activities shall be as follows.
1. Automations to cordon nodes, drain nodes and shutdown cluster
2. Manually restarting the cluster from the cloud provider’s web console
3. Automations to uncordon nodes

@ivandov Please share your inputs. Also, since we have a bash script currently, don't it needs to be converted into an Ansible Playbook(s) for its usage in AAP?
